### ISSUE TITLE
Test failure in listtransactions.py [bug]

### ISSUE THREAD

**Issue by pepecoinppc** [pepecoinppc/pepecoin#1]
# Bug Report

**Current behavior:**
Test failure during Github Actions build

**Expected behavior**
Test should pass during Github Actions build

Run the Github Actions build for the branch `dogecoin-1.14.7-dev`. This branch is a clone of `1.14.7-dev` of the dogecoin repository.
The job that's failing is x86_64-linux-experimental.
Here is a link to the build https://github.com/pepecoinppc/pepecoin/actions/runs/6061079179/job/16445880036

**Comment by pepecoinppc** [comment]
@chromatic

**Comment by pepecoinppc** [comment]
What's interesting is the branch on the dogecoin repo seems to be passing. In the log it says "Account balance insufficient." or something to that effect.

**Comment by chromatic** [comment]
I had to cherry pick [an OpenSSL commit](https://github.com/dogecoin/dogecoin/pull/3079/commits/6f216855bd0730e278de19144ca85d8157a9c02d) to get past one test failure in `make check`. I wonder if there are other commits missing.

**Comment by chromatic** [comment]
Once I pulled in that change and rebuilt, I was able to run the tests locally and see success. I recommend trying that first: make sure the head commit in this repository is the head commit of 1.14.7-dev. Looks like you might have forked from 1.14.6, which probably isn't working with OpenSSL 3.x these days.

**Comment by pepecoinppc** [comment]
Ok I'll try and pull 1.14.7-dev in again and check the commit hash

**Comment by pepecoinppc** [comment]
Ok, I see what you mean. Yeah, the master branch has not been updated. My plan was to merge into master when I get the builds working. The `dogecoin-1.14.7-dev` branch has the correct commit hash `ed85180`. It's the same as `1.14.7-dev`. The build for that branch is here https://github.com/pepecoinppc/pepecoin/actions/runs/6061079179

**Comment by pepecoinppc** [comment]
I'm sorry, let me see if I can give you permission to see the actions. I just realized you can't see it.

**Comment by pepecoinppc** [comment]
I reran the build on branch `new-dogecoin-1.14.7-dev` and the build is passing now. I deleted some whitespace to create a new commit hash, but that was on the head commit of dogecoin:1.14.7-dev

I think we're good now. The error in the previous build mentioned something about insufficient funds. Perhaps the build needs to run twice to add the funds? I'm not sure, but you're welcome to look through the logs.

To be clear,

Branch `dogecoin-1.14.7-dev` failed

Branch `new-dogecoin-1.14.7-dev` succeeds (2 commits ahead of `ed85180`. README.md file change and whitespace deleted change).

Thanks for the help, I appreciate you taking a look on your holiday weekend!
